# Created by: Derek Musselmann aka phrac <derek@disflux.com>
# $FreeBSD$

PORTNAME=	fritzing
PORTVERSION=	0.8.7.b
DISTVERSION=	0.8.7b
CATEGORIES=	cad
MASTER_SITES=	http://fritzing.org/download/0.8.7b/source-tarball/

DISTNAME=	fritzing-0.8.7b.source
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	derek@disflux.com
COMMENT=	xA free as in freedom Skype replacement

LICENSE=	GPLv3

USES=		qmake
USE_QT4=	gui moc_build qmake_build rcc_build uic_build


.include <bsd.port.mk>
