# Created by: Derek Musselmann aka phrac <derek@disflux.com>
# $FreeBSD$

PORTNAME=	euclid-wm
PORTVERSION=	0.4.3
CATEGORIES=	x11-wm
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}

MAINTAINER=	derek@disflux.com
COMMENT=	Tiling window manager with easy keyboard management

.include <bsd.port.mk>
